# Python Basic Review Required for Quantum Coding
This file Demonstrate Basic python concepts of vectors and matrices ,how actually used in quantum computing coding.
So today we'll practice basic python skills and perform matrix and vectors operation needed for quantum computing.
Lets Start from scratch.

## 1. Python Basic Review  
- variables 
- lists 
- Loops 
- function 

In [8]:
#Basic Python refresher start with simple variable and sum them
x=5
y=10
print('Sum=',x+y)


Sum= 15


In [9]:

#Simple Loop -print 0 to 5 number
for i in range(5):
    print('i=',i)

i= 0
i= 1
i= 2
i= 3
i= 4


In [10]:
#Simple function -return square of entire number
def square(n):
    return n*n
print('square(4)=',square(4))

square(4)= 16


## 2. Import NumPy
NumPy is essential for quantum circuit simulations(for Matrix operations).

In [11]:
import numpy as np

## 3.Vector Opeartions
vector is used to represent quantum state .this vector live in mathematical space called hilbert space represent using complex number.now lets practice basic of vectors with simple 2D or 3D matrix.

In [12]:
#Define vectors
v1=np.array([1,2])
v2=np.array([3,4])
print('v1=',v1)
print('v2=',v2)

v1= [1 2]
v2= [3 4]


In [13]:
#lets perform addition of two vector
print('v1+v2=',v1+v2)

v1+v2= [4 6]


In [14]:
#Dot product of vector
print('Dot product=',np.dot(v1,v2))

Dot product= 11


In [16]:
#perform addition on 3D example
u1=np.array([1,0,-1])
u2=np.array([2,3,1])
print('u1+u2=',u1+u2)

u1+u2= [3 3 0]


## 4. 2x2 Matrix Operation
matrix are typically used to represent quantum gates. Quantum computing always prefer square matrix.there are diffent kind of atrix are used in quantum computing such as harmitian matrix,Identity matrix,unitary matrix.so this is most improtant part of quantum coding.

In [20]:
#Define  2x2 matrices
A=np.array([[1,2],[3,4]])
B=np.array([[0,1],[1,0]])#Pauli-X matrix of quantum x-gate
print('A =\n',A)
print('\nB =\n',B)

A =
 [[1 2]
 [3 4]]

B =
 [[0 1]
 [1 0]]


In [21]:
#Addition of matrix
print('\nA +B=\n',A+B)


A +B=
 [[1 3]
 [4 4]]


In [22]:
#Multiplication of matrix
print('\nA * B=\n',A*B)


A * B=
 [[0 2]
 [3 0]]


In [23]:
#Determinant of matrix
print('\n det(A)=',np.linalg.det(A))
print('\n det(B)=',np.linalg.det(B))



 det(A)= -2.0000000000000004

 det(B)= -1.0


## 5. 3x3 matrix Operation
practice with larger matrices

In [26]:
#Define  3x3 matrices
M1=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
M2=np.array([[9,8,7],
            [6,5,4],
            [3,2,1]])
print('M1 =\n',M1)
print('\nM2 =\n',M2)
#Addition of matrix
print('\nAdiition of M1 +vM2=\n',M1+M2)
#Multiplication of matrix
print('\n Multiplication of M1 * M2=\n',M1*M2)
#Determinant of matrix
print('\n Determinant of det(M1)=',np.linalg.det(M1))
print('\n Determinant of det(M2)=',np.linalg.det(M2))


M1 =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

M2 =
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Adiition of M1 +vM2=
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

 Multiplication of M1 * M2=
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

 Determinant of det(M1)= -9.51619735392994e-16

 Determinant of det(M2)= -1.3322676295501906e-15


## 6.Vector + Matrix Multiplication
this important for Quantum state  Unitary evolution

In [30]:
#Matrix Vector Multiplication
U=np.array([[0,1],[1,0]]) #Pauli-X gate matrix
psi =np.array([0,1]) #quantum state |0> as vector
print('U|psi>=',U*psi) 

U|psi>= [[0 1]
 [0 0]]


You succesfully perform  python review ,2x2 nd 3x3 matrices and vector basic operation,vector and matrix multiplcation. you learn how it actually it used with quantum computing. 

### Created By : Shreya Palase
### Summery :
This notebook demonstrate basic of python review for quantum computing.
1. basic python 
2. 2X2 and 3x3 matrix representation
3. addition,multiplication,determinant, dot product for matrices and vector.
4. combine use of vector and matrix 
### Acknowledgemet :
1. IBM Quantum Qiskit textbook
2. Quantum computing for Begginner
#### Date: 26-Nov-2025