# Linear Algebra for Quantum Computing
Today' our goal is  to understand essential linear Algebra used in Quantum computing.previously we seen basic vectors and matrices ,how it works.now we learn how vector and matrices are used in linear algebra  to perform Quantum coding .we study following point:
- vectors and vectors norms
- complex number in quantum state 
- Bras,Kets and inner products
- Tensor products
- Matrices and Unitary Matrices
- Eigenvalues and Eigenvectors
- Representing Qubits as Vectors  
let's deep dive into it.

## Import python libraries
We will used Numpy for linear algebra and complex vector operations.

In [2]:
import numpy as np
np.set_printoptions(precision =3,suppress=True)

# 2. Qubit As vectors
A single qubit represented as a 2-D complex vectors.
$$ |0> = \begin{pmatrix} 1 \\\\ 0 \end{pmatrix}, \quad |1> = \begin{pmatrix} 0 \\\\ 1 \end{pmatrix} $$

In [3]:
ket0 = np.array([[1],[0]] ,dtype=complex)
ket1 = np.array([[0],[1]] ,dtype=complex)
ket0,ket1

(array([[1.+0.j],
        [0.+0.j]]),
 array([[0.+0.j],
        [1.+0.j]]))

# 3.Superposition States
Quantum superposition  means quantum system can be exist in combination of multiple possible state simulteneously until measuement is made.

Example: $|Ψ> = \frac{1}{\sqrt{2}}(|0> + |1>)$

In [4]:
psi = (1/np.sqrt(2)) * (ket0 + ket1)
psi

array([[0.707+0.j],
       [0.707+0.j]])

## 4.Norm of Quantum state 
Quantum state Must be Normalized.so we perfrom norm operation on every quantum state to represent its validity.Quantum state must have **norm = 1**.

In [5]:
norm = np.linalg.norm(psi)
norm

np.float64(0.9999999999999999)

## 5. Inner product (<bra|ket>)
inner product is like vector dot product that we previously seen.it tell us how two system  similar.

In [6]:
inner = np.vdot(ket0,ket1)
inner

np.complex128(0j)

## 6.Tensor Product(⊗)
Tensor product like N X N matrix.it is used to build multi-state qubit system and create another composite system.

In [7]:
two_qubit_state =np.kron(ket0 ,ket1)
two_qubit_state

array([[0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j]])

## 7.Matrices for Quantum Gates
Quantum gate are represented in form of matrices.
Example:   
$X = \begin{pmatrix}0 & 1 \\\\ 1 & 0 \end{pmatrix}$
 
$H = \frac{1}{\sqrt{2}}\begin{pmatrix}1 & 1 \\\\ 1 & -1\end{pmatrix}$

In [10]:
X = np.array([[0,1],[1,0]] , dtype=complex)
H = (1/np.sqrt(2))*np.array([[1,1],[1,-1]] , dtype=complex)
X,H

(array([[0.+0.j, 1.+0.j],
        [1.+0.j, 0.+0.j]]),
 array([[ 0.707+0.j,  0.707+0.j],
        [ 0.707+0.j, -0.707+0.j]]))

## 8.Apply Gate to a Qubit
let apply hadamard gate on Qubit 0 i.e H-Gate on |0> and see what's the result.

In [13]:
H_psi0 = H @ ket0
H_psi0

array([[0.707+0.j],
       [0.707+0.j]])

## 9.Check matrix is Unitary
it is mendatory to check matrix is Unitary or not in qunatum computing.Unitary matrix is the square matrix whose conjugate transpose is also its inverse.it help to norm -preserving.
Unitary: $U^{\dagger}U = I$

In [14]:
def is_unitary(U):
        return np.allclose(U.conj().T @ U,np.eye(U.shape[0]))
is_unitary(H),is_unitary(X)

(True, True)

## 10.Eigenvalues and Eigenvectors
Quantum gate (unitary matrices) often have eigenvalue +1 or -1 or complex phase .its directly connected to quantum measurement. Lets compute them for Puali-X and Hadamard Gate to see how it operate on it.

In [17]:
eignval_X,eignvect_X=np.linalg.eig(X)
eignval_H,eignvect_H=np.linalg.eig(H)
print("Eigenvalues of X:")
print(eignval_X)
print("Eigenvectors of X:")
print(eignvect_X)

print("Eigenvalues of X:")
print(eignval_H)
print("Eigenvectors of X:")
print(eignvect_H)


Eigenvalues of X:
[ 1.+0.j -1.+0.j]
Eigenvectors of X:
[[ 0.707-0.j  0.707+0.j]
 [ 0.707+0.j -0.707+0.j]]
Eigenvalues of X:
[ 1.+0.j -1.+0.j]
Eigenvectors of X:
[[ 0.924+0.j -0.383+0.j]
 [ 0.383-0.j  0.924+0.j]]


Today we learn how to used linear algebra operation in qunatum computing,how it work.do practice for that to get clear understanding of concept which require later.Refer notes to understanding each concept.

### Created By : Shreya Palase
### Summery :
This notebook demonstrate Essential linear Algrbra for quantum computing.
- vectors and vectors norms
- complex number in quantum state 
- Bras,Kets and inner products
- Tensor products
- Matrices and Unitary Matrices
- Eigenvalues and Eigenvectors
- Representing Qubits as Vectors
### Acknowledgemet :
1. IBM Quantum Qiskit textbook
2. Quantum computing for Begginner
#### Date: 26-Nov-2025

Thank you and keep learning.